name: njupt_ios

options:
  bundleIdPrefix: com.njupt.auth
  deploymentTarget:
    iOS: "16.0"

targets:
  njupt_ios:
    type: application
    platform: iOS
    sources:
      - path: njupt_ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.njupt.auth.njupt-ios
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.0"
    info:
      path: njupt_ios/Info.plist
      properties:
        CFBundleName: NJUPT Auth
        CFBundleDisplayName: 校园网快捷认证
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        LSRequiresIPhoneOS: true
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen:
          UIColorName: AccentColor
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
